language: python
python:
  - "3.6"
sudo: enabled
env:
  CODECOV_TOKEN="8904c3db-128a-4d3d-a2ff-d6a922227e4c"
before_install:
  - npm install -g npm@latest
install:
  - make setup-no-input
script: make test
after_success:
  - bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"
branches:
  only:
    - master
    - develop
